### ISSUE TITLE
Docker image pre-built when running action ?

### ISSUE THREAD

**Issue by nvuillam** [UnicornGlobal/has-changes-action#3]
Hi, thanks for your work on the repo :) 

I noticed that the docker image is built from Dockerfile every time has_changes_action is used in a workflow

Couldn't you directly use a pre-built image, so it could just be pulled, and we would gain performances ?

I do that with [Mega-Linter](https://nvuillam.github.io/mega-linter) and it works well :)

I'm pretty sure you can almost copy paste the following files and it would work with a few updates:
- https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-DEV.yml
- https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-PROD.yml
- https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-RELEASE.yml
- https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/versioning.yml
- https://github.com/nvuillam/mega-linter/blob/master/.automation/cleanup-docker.sh
- https://github.com/nvuillam/mega-linter/blob/master/.automation/upload-docker.sh
- https://github.com/nvuillam/mega-linter/blob/master/.automation/validate-docker-labels.sh

**Comment by donovanmuller** [comment]
This seems to be resolved in https://github.com/UnicornGlobal/has-changes-action/commit/25883a0351c2af591038a7eabc04d4ac21894376 ?

**Comment by darrynten** [comment]
@donovanmuller yep, thanks for the reminder :)
