### ISSUE TITLE
Cut release with latest changes

### ISSUE THREAD

**Issue by alexlafroscia** [UnicornGlobal/has-changes-action#4]
Hey! I'd love to make use of the arguments that have been added to this workflow, so that I can filter the list of dirty files based on the `pathspec` input. That doesn't appear to be available on the latest release, though. Could you tag a new release?

**Comment by darrynten** [comment]
Hi there!

I just published a new release that includes that functionality, v1.0.12

**Comment by alexlafroscia** [comment]
Thanks!
